// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/post.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/posts/[id].tsx";
import * as $4 from "./routes/posts/new.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Navbar.tsx";
import * as $$2 from "./islands/NewPost.tsx";
import * as $$3 from "./islands/PostList.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/post.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/posts/[id].tsx": $3,
    "./routes/posts/new.tsx": $4,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Navbar.tsx": $$1,
    "./islands/NewPost.tsx": $$2,
    "./islands/PostList.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
