// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/login.ts";
import * as $2 from "./routes/api/post.ts";
import * as $3 from "./routes/api/register.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/login.tsx";
import * as $6 from "./routes/posts/[id]/edit.tsx";
import * as $7 from "./routes/posts/[id]/index.tsx";
import * as $8 from "./routes/posts/new.tsx";
import * as $$0 from "./islands/LoginForm.tsx";
import * as $$1 from "./islands/Navbar.tsx";
import * as $$2 from "./islands/PostForm.tsx";
import * as $$3 from "./islands/PostList.tsx";
import * as $$4 from "./islands/RegisterForm.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/login.ts": $1,
    "./routes/api/post.ts": $2,
    "./routes/api/register.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/login.tsx": $5,
    "./routes/posts/[id]/edit.tsx": $6,
    "./routes/posts/[id]/index.tsx": $7,
    "./routes/posts/new.tsx": $8,
  },
  islands: {
    "./islands/LoginForm.tsx": $$0,
    "./islands/Navbar.tsx": $$1,
    "./islands/PostForm.tsx": $$2,
    "./islands/PostList.tsx": $$3,
    "./islands/RegisterForm.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
